version: '3.8'
# This is the docker-compose version

# This production file can be used with docker-compose the following way:
# $ docker-compose -f docker-compose-production.yml up --build
services:
  web:
    build: .
    #    command: python /code/manage.py runserver 0.0.0.0:8000
    command: gunicorn djangoSurveysProjectSource.wsgi -b 0.0.0.0:8000
    environment:
      - ENVIRONMENT=production
      - ENV_SECRET_KEY=DJANGO_SECRET_KEY_HERE
      - ENV_DEBUG=0
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: postgres
volumes:
  postgres_data: